// resources/ts/components/settings/tabs/time.tsx
import { DateTime } from 'luxon';
import React, { PureComponent } from 'react';
import { Dispatch } from 'redux';
import { connect } from 'react-redux';

import { RadioWithStore as Radio } from '../controls';

import Settings from '../../../settings';
import { AppState, setOption } from '../../../store';
import { Time as TimeUtils } from '../../../utils';

interface Props {
  readonly settings: Settings;
  readonly onChange: (key: string, value: any) => void;
}

interface State {
  readonly currentTime: string;
}

export class Time extends PureComponent<Props, State> {
  private interval: number;

  public constructor(props: Props) {
    super(props);

    this.state = {
      currentTime: '',
    };
  }

  private updateTime = () => {
    const time = DateTime.fromJSDate(new Date());
    this.setState({
      currentTime: TimeUtils.format(time),
    });
  }

  public componentDidMount() {
    this.interval = setInterval(this.updateTime, 1000);
  }

  public componentWillUnmount() {
    clearInterval(this.interval);
  }

  public render() {
    return (
      <>
        <h3 className="settings-form__option-title">Language</h3>
        <Radio setting="time.locale" value="default">Browser default</Radio>
        <Radio setting="time.locale" value="custom">
          <span>Custom </span>
          <input type="text" className="input settings-form__text" placeholder="en"
            value={this.props.settings.time.localeCustom}
            onChange={e => this.props.onChange('time.localeCustom', e.target.value)} />
        </Radio>

        <h3 className="settings-form__option-title">Format</h3>
        <Radio setting="time.format" value="default">Browser default</Radio>
        <Radio setting="time.format" value="custom">
          <span>Custom </span>
          <input type="text" className="input settings-form__text" placeholder="EEE, dd MMM yyyy HH:mm:ss"
            value={this.props.settings.time.formatCustom}
            onChange={e => this.props.onChange('time.formatCustom', e.target.value)} />
          <p>See the <a href="https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens">luxon documentation</a> for the custom tokens reference.</p>
        </Radio>

        <h3 className="settings-form__option-title">Time zone</h3>
        <Radio setting="time.zone" value="default">Browser default</Radio>
        <Radio setting="time.zone" value="fixed">
          <span>Fixed UTC offset </span>
          <input type="number" className="input settings-form__text" min="-99" max="99"
            value={this.props.settings.time.zoneFixed}
            onChange={e => this.props.onChange('time.zoneFixed', e.target.value)} />
        </Radio>

        <h3 className="settings-form__option-title">Current format</h3>
        <p className="settings-form__row">{this.state.currentTime}</p>
      </>
    );
  }
}

const mapStateToProps = (state: AppState) => {
  return {
    settings: state.settings.settings,
  };
};

const mapDispatchToProps = (dispatch: Dispatch) => {
  return {
    onChange: (key: string, value: any) => dispatch(setOption(key, value)),
  };
};

export const TimeWithStore = connect(
  mapStateToProps,
  mapDispatchToProps
)(Time);

export default TimeWithStore;

// components/settings-form/time.vue
<template>
  <div>
    <h3 class="settings-form__option-title">Language</h3>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.locale" :value="'default'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Browser default
      </x-radio-button>
    </div>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.locale" :value="'custom'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Custom
        <input type="text" class="input settings-form__text" placeholder="en"
          @click="settings.time.locale = 'custom'"
          v-model="settings.time.localeCustom" />
      </x-radio-button>
    </div>

    <h3 class="settings-form__option-title">Format</h3>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.format" :value="'default'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Browser default
      </x-radio-button>
    </div>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.format" :value="'custom'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Custom
        <input type="text" class="input settings-form__text"
          placeholder="EEE, dd MMM yyyy HH:mm:ss"
          @click="settings.time.format = 'custom'"
          v-model="settings.time.formatCustom" />
      </x-radio-button>
    </div>

    <p>
      See the
      <a href="https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens">
        luxon documentation
      </a>
      for the custom tokens reference.
    </p>

    <h3 class="settings-form__option-title">Time zone</h3>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.zone" :value="'default'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Browser default
      </x-radio-button>
    </div>

    <div class="settings-form__row">
      <x-radio-button v-model="settings.time.zone" :value="'fixed'"
        label-class="settings-form__label" input-class="settings-form__radio">
        Fixed UTC offset
        <input type="number" class="input settings-form__text"
          min="-99" max="99"
          @click="settings.time.zone = 'fixed'"
          v-model="settings.time.zoneFixed" />
      </x-radio-button>
    </div>

    <h3 class="settings-form__option-title">Current format</h3>

    <p>{{ time }}</p>
  </div>
</template>

<script lang="ts" src="./time.ts"></script>
